version: '3.4'

networks:
  hids_networks:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16

x-proxy: &proxy
  http_proxy: ${http_proxy}
  https_proxy: ${https_proxy}
  no_proxy: ${no_proxy}

x-base: &base
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "5"
  # https://docs.docker.com/compose/compose-file/#restart
  #restart: on-failure # disable restart for development

volumes:
  rules-data:   # scirius rules
  suricata-logs: #suricata logs
  suricata-socket:
  es-data:      # elasticsearch data
  pcap-storage: # store pcaps

services:
  logstash:
    <<: *base
    # cf.: https://www.elastic.co/guide/en/logstash/current/docker-config.html
    container_name: logstash-hids
    image: logstash-hids
    networks: 
      - hids_networks
    build:
      context: ./logstash
      args:
        <<: *proxy
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash/:/usr/share/logstash/pipeline/
      - suricata-logs:/var/log/suricata:ro
    depends_on:
      - elasticsearch
    environment:
      <<: *proxy
      LOG_LEVEL: info

  elasticsearch:
    <<: *base
    container_name: elasticsearch-hids
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.1
    ports: [ '9200:9200', '9300:9300' ]
    volumes: [ 'es-data:/usr/share/elasticsearch/data' ]
    networks: 
      - hids_networks
    environment:
      # cf.: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-configuration-methods
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      network.host: 0.0.0.0
      node.max_local_storage_nodes: 1
      cluster.name: hids-cluster
      bootstrap.memory_lock: 'true'
      discovery.type: single-node
  
  kibana:
    <<: *base
    container_name: kibana-hids
    image: docker.elastic.co/kibana/kibana-oss:6.5.1
    networks: 
      - hids_networks
    ports: [ '5601:5601' ]
    depends_on: [ elasticsearch ]
    environment:
      <<: *proxy
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200

  evebox:
    <<: *base
    image: jasonish/evebox:latest
    networks: 
      - hids_networks
    ports:
      - "5636:5636"
    depends_on: [ elasticsearch ]
    environment:
      <<: *proxy
      ELASTICSEARCH_URL: http://elasticsearch:9200

  suricata:
    <<: *base
    container_name: suricata-hids
    image: suricata-hids
    build:
      context: ./suricata
      args:
        <<: *proxy
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    volumes:
      - ./config/suricata/suricata.yaml:/etc/suricata/suricata.yaml:ro
      - suricata-logs:/var/log/suricata:rw
      - rules-data:/etc/suricata/rules:rw
      - suricata-socket:/var/run/suricata/suricata-command.socket:rw
    environment:
      <<: *proxy
      INTERFACE_NAME: enp0s3

  scirius:
    <<: *base
    container_name: scirius-hids
    image: scirius-hids
    networks: 
      - hids_networks
    depends_on:
      - suricata
    build:
      context: ./scirius
      args:
        <<: *proxy
    ports:
      - "8000:8000"
    volumes:
      - ./config/scirius/local_settings.py:/opt/selks/scirius/scirius/local_settings.py:ro
      - rules-data:/etc/suricata/rules:rw
      - suricata-socket:/var/run/suricata/suricata-command.socket:rw
    environment:
      <<: *proxy