version: '3.4'

x-proxy: &proxy
  http_proxy: ${http_proxy}
  https_proxy: ${https_proxy}
  no_proxy: ${no_proxy}

x-base: &base
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "5"
  # https://docs.docker.com/compose/compose-file/#restart
  #restart: on-failure # disable restart for development

volumes:
  json-data:    # suricata json input -> logstash
  rules-data:   # scirius rules
  suricata-logs: #suricata logs
  es-data:      # elasticsearch data
  pcap-storage: # store pcaps

services:
  logstash:
    <<: *base
    # cf.: https://www.elastic.co/guide/en/logstash/current/docker-config.html
    container_name: logstash-hids
    image: docker.elastic.co/logstash/logstash-oss:6.5.1
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash/:/usr/share/logstash/pipeline/
      - json-data:/var/log/suricata:ro
    hostname: hids.logstash
    depends_on:
      - elasticsearch
    environment:
      LOG_LEVEL: info

  elasticsearch:
    <<: *base
    container_name: elasticsearch-hids
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.1
    ports: [ '9200:9200', '9300:9300' ]
    volumes: [ 'es-data:/usr/share/elasticsearch/data' ]
    hostname: hids.elasticsearch
    environment:
      # cf.: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-configuration-methods
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      network.host: 0.0.0.0
      node.max_local_storage_nodes: 1
      cluster.name: hids-cluster
      bootstrap.memory_lock: 'true'
      discovery.type: single-node

  suricata:
    <<: *base
    container_name: suricata-hids
    image: suricata-hids
    build:
      context: ./suricata
      args:
        <<: *proxy
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    volumes:
      - suricata-logs:/var/log/suricata:rw
      - rules-data:/etc/suricata/rules:rw
    environment:
      <<: *proxy

  scirius:
    <<: *base
    container_name: scirius-hids
    image: scirius-hids
    hostname: hids.scirius
    depends_on:
      - suricata
    build:
      context: ./scirius
      args:
        <<: *proxy
    ports:
      - "8000:8000"
    volumes:
      - ./config/scirius/local_settings.py:/opt/selks/scirius/scirius/local_settings.py:ro
      - rules-data:/etc/suricata/rules:rw
    environment:
      <<: *proxy